Repository StaticMania/keep-react, pull requests merged in 2023-11, with the labels that each got.

#15 Add styling to code snippets in README.md
  README.md
Labels: improvements

#28 [Update] : Carousel Spelling Mistake Solve
  .gitignore
  app/docs/components/carousel/carousel.mdx
  app/docs/components/carousel/variant/CarouselWithTextControl.tsx
  public/data/search.json
Labels: documentation

#27 Update: Installition documentation update
  app/docs/getting-started/Introduction/Code/Code.tsx
  app/docs/getting-started/Introduction/Introduction.mdx
  app/docs/getting-started/Introduction/page.tsx
  components/CopyCode.tsx
Labels: documentation, improvements

#50 Fixed: Home Page Responsive Issue Fixed
  app/page.tsx
  components/ComponentsList.tsx
  components/Navbar.tsx
  routes/routes.ts
Labels: improvements

#58 Fixed: Dropdown-overlapping navbar
  src/components/Dropdown/theme.ts
Labels: bug, improvements

#66 (KR - #65 ) Changelog documentation added
  CHANGELOG.md
Labels: documentation

#77 (KR-#76) : Card component font issue fixed
  .gitignore
  app/docs/components/card/variant/HorizontalCard.tsx
  app/docs/components/card/variant/ProductCard.tsx
  app/docs/components/card/variant/ProfileCard.tsx
  app/docs/components/card/variant/ProfileCardWithCover.tsx
Labels: documentation, improvements

#84 add modal open animation
  src/components/Modal/theme.ts
  tailwind.config.js
Labels: feature, improvements

#86 fix: tabs buttons blinking issue
  src/components/Tabs/theme.ts
Labels: improvements

#88 Fixed: Date Picker width issue
  components/ComponentsList.tsx
Labels: bug, documentation, improvements
