Repository StaticMania/keep-react, pull requests merged in 2023-12, with the labels that each got.

#94 Fixed: Discord link expire issue fixed
  components/Navbar.tsx
  public/images/icon/discord.svg
Labels: invalid, improvements

#97 Added: Contributor img added
  app/page.tsx
Labels: improvements

#100 Keep/storybook control
  src/components/Accordion/Accordion.stories.tsx
  src/components/Alert/Alert.stories.tsx
  src/components/Avatar/Avatar.stories.tsx
  src/components/Badge/Badge.stories.tsx
  src/components/Breadcrumb/Breadcrumb.stories.tsx
  src/components/Button/Button.stories.tsx
  src/components/Card/Card.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Chart/AreaCharts.stories.tsx
  src/components/Chart/BarChart.stories.tsx
  src/components/CheckBox/CheckBox.stories.tsx
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Empty/Empty.stories.tsx
  src/components/FormControls/Radio.stories.tsx
  src/components/FormControls/TextArea.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Navigation/Navigation.stories.tsx
  src/components/Notification/Notification.stories.tsx
  src/components/Pagination/Pagination.stories.tsx
  src/components/PlayButton/PlayButton.stories.tsx
  src/components/Popover/Popover.stories.tsx
  src/components/Progress/Progress.stories.tsx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/Sidebar/Sidebar.stories.tsx
  src/components/Skeleton/Skeleton.stories.tsx
  src/components/Slider/Slider.stories.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Statistic/Statistic.stories.tsx
  src/components/Steps/Steps.stories.tsx
  src/components/Switch/Switch.stories.tsx
  src/components/Table/Table.stories.tsx
  src/components/Tag/Tag.stories.tsx
  src/components/Timeline/Timeline.stories.tsx
  src/components/Tree/Tree.stories.tsx
  src/components/Upload/Upload.stories.tsx
Labels: documentation

#103 Related issue 90 feat: add focus when search field was opened
  components/Search.tsx
Labels: feature

#111 Issue: Checkbox transition issue fixed.
  app/src/components/CheckBox/theme.ts
Labels: improvements

#116 Documentation Page Design Updated.
  app/components/CodePreview.tsx
  app/components/Navbar.tsx
  app/docs.css
  app/docs/components/notification/variant/DefaultNotification.tsx
  app/docs/components/notification/variant/NotificationWithIcon.tsx
  app/docs/layout.tsx
  app/globals.css
  app/page.tsx
  mdx-components.tsx
Labels: documentation
